name: slot_machine
version: 5.0.1
author: Filip Hracek <filip.hracek@gmail.com>
description: >
  A simple, self-contained class that allows user to put a simple slot machine
  animation to the DOM.
homepage: https://github.com/filiph/slot_machine
environment:
  sdk: '>=1.24.0 <3.0.0'
dev_dependencies:
  build_runner: '>=0.8.10 <0.10.0'
  build_web_compilers: '>=0.3.6 <0.5.0'
  test: '>=0.12.19 <2.0.0'
