name: slot_machine
version: 1.0.1
author: Filip Hracek <filip.hracek@gmail.com>
description: A simple, self-contained class that allows user to put a simple slot machine to the DOM.
homepage: https://github.com/filiph/slot_machine
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
