name: slot_machine
version: 2.1.0
author: Filip Hracek <filip.hracek@gmail.com>
description: >
  A simple, self-contained class that allows user to put a simple slot machine
  to the DOM.
homepage: https://github.com/filiph/slot_machine
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  browser: ^0.10.0+2
